[package]
name = "swarms-rs"
version = "0.1.0"
edition = "2024"
description = "Rust implementation of the Swarms framework for building multi-agent systems"
license = "MIT"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
dashmap = { version = "6", features = ["serde"] }
tokio = { version = "1" }
serde = { version = "1", features = ["derive"] }
erased-serde = "0.4"
sysinfo = "0.33"
schemars = "=1.0.0-alpha.17"
serde_json = "1"
thiserror = "2"
tracing = "0.1"
twox-hash = "2.1"
futures = "0.3"
uuid = { version = "1.15", features = ["v4", "serde"] }
zstd = "0.13.3"
reqwest = { version = "0.12", features = [
    "json",
    "stream",
    "multipart",
    "rustls-tls-native-roots",
], default-features = false }
petgraph = { version = "0.7", default-features = false, features = [
    "stable_graph",
] }

# llm provider
async-openai = { version = "0.28", features = ["byot"] }

# swarms
swarms-macro = { path = "../swarms-macro" }


[dev-dependencies]
anyhow = "1"
console-subscriber = "0.4.1"
dotenv = "0.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "tracing"] }
tokio-test = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
mockall = "0.13"
criterion = "0.5"

[[bench]]
name = "graph_workflow_benchmarks"
harness = false
