[package]
name = "swarms-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swarms-rs = { path = "../swarms-rs" }
swarms-macro = { path = "../swarms-macro" }
thiserror = "2"
